-- MySQL 8.0 schema
DROP DATABASE IF EXISTS pharma_sales_analytics; CREATE DATABASE pharma_sales_analytics; USE pharma_sales_analytics;
CREATE TABLE reps (rep_id VARCHAR(10) PRIMARY KEY, rep_name VARCHAR(100), territory VARCHAR(60), region VARCHAR(30), base_city VARCHAR(60), manager VARCHAR(100), experience_years INT, rep_effectiveness_index DECIMAL(6,3));
CREATE TABLE doctors (doctor_id VARCHAR(10) PRIMARY KEY, doctor_name VARCHAR(120), specialty VARCHAR(60), potential_class CHAR(1), practice_years INT, territory VARCHAR(60), region VARCHAR(30), city VARCHAR(60));
CREATE TABLE products (product_id VARCHAR(10) PRIMARY KEY, product_name VARCHAR(100), category VARCHAR(60), avg_unit_price DECIMAL(12,2));
CREATE TABLE call_activity (activity_id VARCHAR(12) PRIMARY KEY, rep_id VARCHAR(10), doctor_id VARCHAR(10), product_id VARCHAR(10), meeting_date DATE, calls INT, visits INT, samples_distributed INT, meeting_type VARCHAR(30), engagement_score DECIMAL(6,3), FOREIGN KEY(rep_id) REFERENCES reps(rep_id), FOREIGN KEY(doctor_id) REFERENCES doctors(doctor_id), FOREIGN KEY(product_id) REFERENCES products(product_id));
CREATE TABLE sales (sale_id VARCHAR(12) PRIMARY KEY, activity_id VARCHAR(12), rep_id VARCHAR(10), doctor_id VARCHAR(10), product_id VARCHAR(10), sale_date DATE, month DATE, territory VARCHAR(60), region VARCHAR(30), units_sold INT, revenue DECIMAL(14,2), FOREIGN KEY(activity_id) REFERENCES call_activity(activity_id), FOREIGN KEY(rep_id) REFERENCES reps(rep_id), FOREIGN KEY(doctor_id) REFERENCES doctors(doctor_id), FOREIGN KEY(product_id) REFERENCES products(product_id));
CREATE TABLE incentive_compensation (incentive_id VARCHAR(12) PRIMARY KEY, rep_id VARCHAR(10), month DATE, target_revenue DECIMAL(14,2), actual_revenue DECIMAL(14,2), achievement_pct DECIMAL(10,2), bonus DECIMAL(14,2), performance_band VARCHAR(40), FOREIGN KEY(rep_id) REFERENCES reps(rep_id));
CREATE INDEX idx_sales_rep_month ON sales(rep_id,month); CREATE INDEX idx_sales_territory_month ON sales(territory,month); CREATE INDEX idx_calls_doctor ON call_activity(doctor_id);
